Repository European-XFEL/EXtra-foam, pull requests merged in 2020-03, with the labels that each got.

#74 Fixes #73
  extra_foam/pipeline/processors/tests/test_binning.py
Labels: bug

#75 Use nansum in TrXAS analysis
  extra_foam/pipeline/processors/tests/test_trxas.py
  extra_foam/pipeline/processors/tr_xas.py
Labels: bug

#76 Fix gain/offset slicer for train-resolved detector.
  extra_foam/algorithms/imageproc_py.py
  extra_foam/algorithms/tests/test_image_proc.py
  extra_foam/gui/ctrl_widgets/calibration_ctrl_widget.py
  extra_foam/gui/image_tool/tests/test_image_tool.py
  extra_foam/pipeline/processors/image_processor.py
  extra_foam/pipeline/processors/tests/test_image_processor.py
  extra_foam/pipeline/tests/__init__.py
Labels: bug

#77 Display n processed and dropped
  extra_foam/database/db_utils.py
  extra_foam/database/mondata.py
  extra_foam/gui/image_tool/bulletin_view.py
  extra_foam/gui/image_tool/tests/test_image_tool.py
  extra_foam/pipeline/worker.py
Labels: feature

#78 Enable train-resolved FOM filter
  extra_foam/database/metadata.py
  extra_foam/gui/ctrl_widgets/__init__.py
  extra_foam/gui/ctrl_widgets/filter_ctrl_widget.py
  extra_foam/gui/main_gui.py
  extra_foam/gui/mediator.py
  extra_foam/gui/tests/test_main_gui.py
  extra_foam/pipeline/processors/__init__.py
  extra_foam/pipeline/processors/base_processor.py
  extra_foam/pipeline/processors/control_data.py
  extra_foam/pipeline/processors/digitizer.py
  extra_foam/pipeline/processors/fom_filter.py
  extra_foam/pipeline/processors/pulse_filter.py
  extra_foam/pipeline/processors/tests/test_fom_filter.py
  extra_foam/pipeline/processors/tests/test_pulse_filter.py
  extra_foam/pipeline/processors/tests/test_pump_probe.py
  extra_foam/pipeline/processors/xgm.py
  extra_foam/pipeline/worker.py
Labels: feature

#80 Fix pulse-filter in digitizer
  extra_foam/pipeline/data_model.py
  extra_foam/pipeline/processors/digitizer.py
  extra_foam/pipeline/processors/tests/test_digitizer.py
  extra_foam/pipeline/tests/test_data_model.py
Labels: bug

#70 0.8.0 Release
  docs/analysis_type.rst
  docs/changelog.rst
  docs/images/1D_binning_window.png
  docs/images/ImageTool.png
  docs/images/MainGUI.png
  docs/images/binning_window.png
  docs/images/correlation_setup.png
  docs/images/correlation_window.png
  docs/images/histogram_setup.png
  docs/images/histogram_window.png
  docs/images/poi_window.png
  docs/images/pump-probe_window.png
  docs/images/pump_probe_pattern.png
  docs/images/pump_probe_window.png
  docs/introduction.rst
  docs/main_gui.rst
  docs/pump_probe.rst
  docs/statistics.rst
  docs/tutorial_data_flow.rst
  extra_foam/__init__.py
Labels: release

#85 Fix display bug in ImageTool
  extra_foam/gui/image_tool/corrected_view.py
Labels: bug

#86 Hotfix 0.8.0.1
  benchmarks/benchmark_demo.ipynb
  docs/changelog.rst
  extra_foam/__init__.py
  setup.py
Labels: release

#90 Support ePix100 detector in EXtra-foam
  README.md
  docs/introduction.rst
  extra_foam/config.py
  extra_foam/configs/mid.config.yaml
  extra_foam/offline/file_server.py
  extra_foam/pipeline/processors/image_assembler.py
  extra_foam/pipeline/processors/tests/test_image_assembler.py
Labels: feature

#93 Implement Master and Slave ROI FOM scan
  docs/image_tool.rst
  docs/statistics.rst
  extra_foam/config.py
  extra_foam/gui/ctrl_widgets/roi_fom_ctrl_widget.py
  extra_foam/gui/image_tool/tests/test_image_tool.py
  extra_foam/gui/mediator.py
  extra_foam/gui/plot_widgets/plot_items.py
  extra_foam/gui/pyqtgraph/graphicsItems/ViewBox/ViewBox.py
  extra_foam/gui/tests/test_main_gui.py
  extra_foam/gui/windows/correlation_w.py
  extra_foam/gui/windows/tests/test_plot_windows.py
  extra_foam/pipeline/data_model.py
  extra_foam/pipeline/processors/correlation.py
  extra_foam/pipeline/processors/image_roi.py
  extra_foam/pipeline/processors/tests/test_correlation.py
  extra_foam/pipeline/worker.py
Labels: feature

#96 Roi fom normalization
  docs/image_tool.rst
  extra_foam/gui/ctrl_widgets/roi_fom_ctrl_widget.py
  extra_foam/pipeline/processors/image_roi.py
  extra_foam/pipeline/processors/tests/test_image_roi.py
Labels: feature

#103 Add ROI1_DIV_ROI2 to ROI FOM
  extra_foam/algorithms/__init__.py
  extra_foam/algorithms/statistics_py.py
  extra_foam/algorithms/tests/test_statistics.py
  extra_foam/config.py
  extra_foam/gui/ctrl_widgets/roi_fom_ctrl_widget.py
  extra_foam/pipeline/processors/fom_filter.py
  extra_foam/pipeline/processors/histogram.py
  extra_foam/pipeline/processors/image_roi.py
  extra_foam/pipeline/processors/tests/test_image_roi.py
Labels: feature

#104 Reset the image mask in case of different shapes if it is empty
  extra_foam/gui/image_tool/tests/test_image_tool.py
  extra_foam/pipeline/processors/image_processor.py
Labels: enhancement

#102 Implement AGIPD 1M geometry in C++
  benchmarks/benchmark_geometry.py
  extra_foam/configs/mid.config.yaml
  extra_foam/configs/spb.config.yaml
  extra_foam/geometries/__init__.py
  extra_foam/geometries/tests/test_1M_geometry.py
  extra_foam/gui/ctrl_widgets/geometry_ctrl_widget.py
  extra_foam/pipeline/processors/image_assembler.py
  extra_foam/pipeline/processors/tests/test_image_assembler.py
  src/extra_foam/f_geometry.cpp
  src/extra_foam/include/f_geometry.hpp
  test/test_geometry.cpp
Labels: feature

#87 Implement save and load metadata.
  extra_foam/config.py
  extra_foam/database/base_proxy.py
  extra_foam/database/metadata.py
  extra_foam/database/tests/test_metadata.py
  extra_foam/gui/ctrl_widgets/analysis_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/azimuthal_integ_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/base_ctrl_widgets.py
  extra_foam/gui/ctrl_widgets/bin_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/calibration_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/correlation_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/filter_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/geometry_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/histogram_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/image_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/pump_probe_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/roi_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/roi_fom_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/roi_hist_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/roi_norm_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/roi_proj_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/smart_widgets.py
  extra_foam/gui/gui_helpers.py
  extra_foam/gui/image_tool/image_tool.py
  extra_foam/gui/image_tool/tests/test_image_tool.py
  extra_foam/gui/main_gui.py
  extra_foam/gui/mediator.py
  extra_foam/gui/misc_widgets/__init__.py
  extra_foam/gui/misc_widgets/configurator.py
  extra_foam/gui/misc_widgets/tests/test_configurator.py
  extra_foam/gui/tests/test_helper_functions.py
  extra_foam/gui/tests/test_main_gui.py
  extra_foam/pipeline/processors/image_assembler.py
  extra_foam/pipeline/processors/image_processor.py
  extra_foam/pipeline/processors/image_roi.py
  extra_foam/pipeline/processors/pump_probe.py
  extra_foam/pipeline/processors/tests/test_histogram.py
  extra_foam/pipeline/processors/tests/test_image_assembler.py
  extra_foam/pipeline/processors/tests/test_pump_probe.py
Labels: feature

#105 0.8.1 release
  docs/changelog.rst
  docs/images/configurator.png
  docs/introduction.rst
  docs/main_gui.rst
  docs/start.rst
  extra_foam/__init__.py
  setup.py
Labels: release

#112 Update .travis.yml
  .travis.yml
Labels: bug

#115 DOC: update documentation
  docs/developer.rst
  docs/image_tool.rst
  docs/introduction.rst
  docs/pump_probe.rst
  docs/start.rst
Labels: documentation

#110 Mask tile edge
  benchmarks/benchmark_geometry.py
  docs/image_tool.rst
  extra_foam/geometries/__init__.py
  extra_foam/geometries/tests/test_1M_geometry.py
  extra_foam/gui/ctrl_widgets/base_ctrl_widgets.py
  extra_foam/gui/ctrl_widgets/geometry_ctrl_widget.py
  extra_foam/gui/ctrl_widgets/image_ctrl_widget.py
  extra_foam/gui/image_tool/image_tool.py
  extra_foam/gui/image_tool/tests/test_image_tool.py
  extra_foam/gui/main_gui.py
  extra_foam/gui/mediator.py
  extra_foam/pipeline/processors/image_assembler.py
  extra_foam/pipeline/processors/tests/test_image_assembler.py
  src/extra_foam/f_geometry.cpp
  src/extra_foam/include/f_geometry.hpp
  test/test_geometry.cpp
Labels: feature

#119 Add standard deviation and variance into ROI FOM
  docs/image_tool.rst
  extra_foam/algorithms/__init__.py
  extra_foam/algorithms/statistics_py.py
  extra_foam/config.py
  extra_foam/gui/ctrl_widgets/roi_fom_ctrl_widget.py
  extra_foam/pipeline/processors/image_roi.py
  extra_foam/pipeline/processors/tests/test_image_roi.py
  extra_foam/pipeline/tests/__init__.py
Labels: feature

#122 Generalize file server
  extra_foam/config.py
  extra_foam/gui/ctrl_widgets/data_source_widget.py
  extra_foam/gui/icons/file_stream.png
  extra_foam/gui/main_gui.py
  extra_foam/gui/mediator.py
  extra_foam/gui/tests/test_main_gui.py
  extra_foam/gui/windows/__init__.py
  extra_foam/gui/windows/base_window.py
  extra_foam/gui/windows/file_stream_controller_w.py
  extra_foam/gui/windows/tests/test_satellite_windows.py
  extra_foam/offline/__init__.py
  extra_foam/offline/file_server.py
  extra_foam/offline/tests/__init__.py
  extra_foam/offline/tests/test_filerserver.py
  extra_foam/services.py
Labels: feature

#125 Simplify imageproc binding
  src/extra_foam/f_imageproc.cpp
Labels: enhancement

#129 Tweak geometry assembling
  extra_foam/geometries/tests/test_1M_geometry.py
  extra_foam/gui/ctrl_widgets/geometry_ctrl_widget.py
  src/extra_foam/f_geometry.cpp
  src/extra_foam/include/f_geometry.hpp
Labels: enhancement

#131 Bump EXtra-data version to 1.0.0 and remove duplicated code
  extra_foam/geometries/tests/test_1M_geometry.py
  extra_foam/pipeline/processors/image_assembler.py
  setup.py
Labels: enhancement

#101 add_support_for_fast_adc
  extra_foam/pipeline/data_model.py
  extra_foam/pipeline/processors/digitizer.py
  extra_foam/pipeline/processors/tests/test_digitizer.py
  extra_foam/pipeline/processors/tests/test_xgm.py
  extra_foam/pipeline/processors/xgm.py
Labels: feature

#130 DOC: update documentation
  docs/images/data_source_from_bridge.png
  docs/images/data_source_from_file.png
  docs/images/file_stream.png
  docs/images/file_stream_control.png
  docs/index.rst
  docs/main_gui.rst
  docs/special.rst
  docs/special_suite.rst
  docs/stream_data.rst
  extra_foam/gui/windows/file_stream_controller_w.py
Labels: documentation
